git/ladder/config/routes.rb
Rails.application.routes.draw do
  resources :memos
  root 'ladder#index'

  # get '/admin/sync', to: 'admin#sync_dingtalk_users'
  # post '/admin/ticket', to: 'admin#query_jsapi_ticket'
  # post '/admin/jsapiconfig', to: 'admin#request_jsapi_config'
  get '/admin/grades/waiting', to: 'user#all_waiting_grades'
  post '/admin/grades/waiting/post', to: 'user#all_waiting_grades_data'
  post '/admin/grade/status', to: 'admin#grade_all_status'
  get '/admin/grades/punish', to: 'user#punish'

  get '/ladder/scores', to: 'ladder#realtime_score'

  get '/user', to: 'user#main'
  get '/user/:user_id', to: 'user#request_grade'
  post '/user/:user_id/post', to: 'user#add_grade'
  get '/user/:user_id/grades/waiting', to: 'user#waiting_grades'
  post '/user/:user_id/grades/waiting/post', to: 'user#waiting_grades_data'
  get '/user/:grade_id/details', to: 'user#grade_details'
  post '/user/:grade_id/details/post', to: 'user#grade_details_data'
  post '/user/:grade_id/details/update/status', to: 'user#grade_status_update'
  get '/user/:user_id/grades/proved', to: 'user#proved_grades'
  post '/user/:user_id/grades/proved/post', to: 'user#proved_grades_data'

  get '/group/graduates', to: 'user#graduates'
  get '/group/graduates/scores', to: 'user#graduates_scores'

  get '/all-valid-users', to: 'user#find_all_valid_users'

  get '/react/hello', to: 'react#hello'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

git/ladder/app/models/memo.rb
class Memo
  include Mongoid::Document
  field :content, type: String
end

git/ladder/app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :set_memo, only: [:show, :edit, :update, :destroy]

  # GET /memos
  # GET /memos.json
  def index
    @memos = Memo.all
  end

  # GET /memos/1
  # GET /memos/1.json
  def show
  end

  # GET /memos/new
  def new
    @memo = Memo.new
  end

  # GET /memos/1/edit
  def edit
  end

  # POST /memos
  # POST /memos.json
  def create
    @memo = Memo.new(memo_params)

    respond_to do |format|
      if @memo.save
        format.html { redirect_to @memo, notice: 'Memo was successfully created.' }
        format.json { render :show, status: :created, location: @memo }
      else
        format.html { render :new }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memos/1
  # PATCH/PUT /memos/1.json
  def update
    respond_to do |format|
      if @memo.update(memo_params)
        format.html { redirect_to @memo, notice: 'Memo was successfully updated.' }
        format.json { render :show, status: :ok, location: @memo }
      else
        format.html { render :edit }
        format.json { render json: @memo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memos/1
  # DELETE /memos/1.json
  def destroy
    @memo.destroy
    respond_to do |format|
      format.html { redirect_to memos_url, notice: 'Memo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_memo
      @memo = Memo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def memo_params
      params.require(:memo).permit(:content)
    end
end

git/ladder/app/helpers/memos_helper.rb
module MemosHelper
end

git/ladder/app/views/memos/_form.html.erb
<%= form_for(memo) do |f| %>
  <% if memo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(memo.errors.count, "error") %> prohibited this memo from being saved:</h2>

      <ul>
      <% memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

git/ladder/app/views/memos/edit.html.erb
<h1>Editing Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Show', @memo %> |
<%= link_to 'Back', memos_path %>

git/ladder/app/views/memos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memos</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memos.each do |memo| %>
      <tr>
        <td><%= memo.content %></td>
        <td><%= link_to 'Show', memo %></td>
        <td><%= link_to 'Edit', edit_memo_path(memo) %></td>
        <td><%= link_to 'Destroy', memo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Memo', new_memo_path %>

git/ladder/app/views/memos/new.html.erb
<h1>New Memo</h1>

<%= render 'form', memo: @memo %>

<%= link_to 'Back', memos_path %>

git/ladder/app/views/memos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @memo.content %>
</p>

<%= link_to 'Edit', edit_memo_path(@memo) %> |
<%= link_to 'Back', memos_path %>